version: "3.8"

services:
  jenkins:
    image: jenkins-with-node # Asegúrate de que este nombre coincida con la imagen personalizada
    container_name: jenkins
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Asegúrate de que el socket de Docker esté montado correctamente
    networks:
      - jenkins_network

  nginx:
    image: nginx:latest
    container_name: nginx
    user: root
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/usr/share/nginx/html
    networks:
      - jenkins_network

  nodejs:
    image: node:16
    container_name: nodejs
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - NVM_DIR=/usr/local/nvm
    command:
      [
        "bash",
        "-c",
        "source $NVM_DIR/nvm.sh && nvm install 16 && npm install && npm start",
      ]
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
